// Code generated by AI. DO NOT EDIT manually without reading the generation guide.
//
// This file contains jlexer streaming parsers for the structs defined in:
//   pkg/types/anthropic/messages_response.go
//
// Source file SHA-256: 412cb28ff80bf6d58fffaadfed7ca17c942609ecda640835bd257ebc373144f5
//
// Generation guide: pkg/types/JLEXER_PARSER_GUIDE.md
// Polymorphic field patterns: pkg/types/UNION_TYPES.md
//
// If the struct definitions in the source file change, regenerate this file
// following the generation guide. Verify the source hash with:
//   shasum -a 256 pkg/types/anthropic/messages_response.go

package anthropic

import (
	"github.com/mailru/easyjson/jlexer"
)

func (r *ClaudeMessagesResponse) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
				r.ID = ""
			} else {
				r.ID = in.String()
			}
		case "type":
			if in.IsNull() {
				in.Skip()
				r.Type = ""
			} else {
				r.Type = in.String()
			}
		case "role":
			if in.IsNull() {
				in.Skip()
				r.Role = ""
			} else {
				r.Role = in.String()
			}
		case "content":
			r.Content = parseContentBlockArrayJLexer(in)
		case "model":
			if in.IsNull() {
				in.Skip()
				r.Model = ""
			} else {
				r.Model = in.String()
			}
		case "stop_reason":
			if in.IsNull() {
				in.Skip()
				r.StopReason = ""
			} else {
				r.StopReason = in.String()
			}
		case "stop_sequence":
			if in.IsNull() {
				in.Skip()
				r.StopSequence = nil
			} else {
				v := in.String()
				r.StopSequence = &v
			}
		case "usage":
			if in.IsNull() {
				in.Skip()
				r.Usage = nil
			} else {
				r.Usage = &Usage{}
				r.Usage.ParseJLexer(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (u *Usage) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "input_tokens":
			if in.IsNull() {
				in.Skip()
				u.InputTokens = nil
			} else {
				v := in.Int64()
				u.InputTokens = &v
			}
		case "output_tokens":
			if in.IsNull() {
				in.Skip()
				u.OutputTokens = nil
			} else {
				v := in.Int64()
				u.OutputTokens = &v
			}
		case "cache_creation_input_tokens":
			if in.IsNull() {
				in.Skip()
				u.CacheCreationInputTokens = nil
			} else {
				v := in.Int64()
				u.CacheCreationInputTokens = &v
			}
		case "cache_read_input_tokens":
			if in.IsNull() {
				in.Skip()
				u.CacheReadInputTokens = nil
			} else {
				v := in.Int64()
				u.CacheReadInputTokens = &v
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (e *ClaudeMessagesStreamEvent) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				e.Type = ""
			} else {
				e.Type = in.String()
			}
		case "message":
			if in.IsNull() {
				in.Skip()
				e.Message = nil
			} else {
				e.Message = &ClaudeMessagesResponse{}
				e.Message.ParseJLexer(in)
			}
		case "index":
			if in.IsNull() {
				in.Skip()
				e.Index = nil
			} else {
				v := in.Int()
				e.Index = &v
			}
		case "content_block":
			e.ContentBlock = parseContentBlockParamJLexer(in)
		case "delta":
			if in.IsNull() {
				in.Skip()
				e.Delta = nil
			} else {
				e.Delta = &DeltaUnion{}
				e.Delta.ParseJLexer(in)
			}
		case "usage":
			if in.IsNull() {
				in.Skip()
				e.Usage = nil
			} else {
				e.Usage = &Usage{}
				e.Usage.ParseJLexer(in)
			}
		case "error":
			if in.IsNull() {
				in.Skip()
				e.Error = nil
			} else {
				e.Error = &APIError{}
				e.Error.ParseJLexer(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (d *DeltaUnion) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		// ContentBlockDelta fields
		case "type":
			if in.IsNull() {
				in.Skip()
				d.Type = ""
			} else {
				d.Type = in.String()
			}
		case "text":
			if in.IsNull() {
				in.Skip()
				d.Text = nil
			} else {
				v := in.String()
				d.Text = &v
			}
		case "partial_json":
			if in.IsNull() {
				in.Skip()
				d.PartialJSON = nil
			} else {
				v := in.String()
				d.PartialJSON = &v
			}
		case "thinking":
			if in.IsNull() {
				in.Skip()
				d.Thinking = nil
			} else {
				v := in.String()
				d.Thinking = &v
			}
		case "signature":
			if in.IsNull() {
				in.Skip()
				d.Signature = nil
			} else {
				v := in.String()
				d.Signature = &v
			}
		// MessageDelta fields
		case "stop_reason":
			if in.IsNull() {
				in.Skip()
				d.StopReason = nil
			} else {
				v := in.String()
				d.StopReason = &v
			}
		case "stop_sequence":
			if in.IsNull() {
				in.Skip()
				d.StopSequence = nil
			} else {
				v := in.String()
				d.StopSequence = &v
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (e *APIError) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				e.Type = ""
			} else {
				e.Type = in.String()
			}
		case "message":
			if in.IsNull() {
				in.Skip()
				e.Message = ""
			} else {
				e.Message = in.String()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
