// Code generated by AI. DO NOT EDIT manually without reading the generation guide.
//
// This file contains jlexer streaming parsers for the structs defined in:
//   pkg/types/anthropic/messages_request.go
//
// Source file SHA-256: 9da00f0c46e523df03e49f7a72205d86d209f0fa724b6fffa08f02e48e6de7af
//
// Generation guide: pkg/types/JLEXER_PARSER_GUIDE.md
// Polymorphic field patterns: pkg/types/UNION_TYPES.md
//
// If the struct definitions in the source file change, regenerate this file
// following the generation guide. Verify the source hash with:
//   shasum -a 256 pkg/types/anthropic/messages_request.go

package anthropic

import (
	"encoding/json"

	"github.com/mailru/easyjson/jlexer"
)

func (r *ClaudeMessagesRequest) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "max_tokens":
			r.MaxTokens = in.Int64()
		case "messages":
			if in.IsNull() {
				in.Skip()
				r.Messages = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					r.Messages = make([]*MessageParam, 0, 4)
				} else {
					r.Messages = []*MessageParam{}
				}
				for !in.IsDelim(']') {
					m := &MessageParam{}
					m.ParseJLexer(in)
					r.Messages = append(r.Messages, m)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "model":
			if in.IsNull() {
				in.Skip()
				r.Model = ""
			} else {
				r.Model = in.String()
			}
		case "system":
			r.System = parseSystemContentJLexer(in)
		case "temperature":
			if in.IsNull() {
				in.Skip()
				r.Temperature = nil
			} else {
				v := in.Float64()
				r.Temperature = &v
			}
		case "top_k":
			if in.IsNull() {
				in.Skip()
				r.TopK = nil
			} else {
				v := in.Int64()
				r.TopK = &v
			}
		case "top_p":
			if in.IsNull() {
				in.Skip()
				r.TopP = nil
			} else {
				v := in.Float64()
				r.TopP = &v
			}
		case "stop_sequences":
			if in.IsNull() {
				in.Skip()
				r.StopSequences = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					r.StopSequences = make([]string, 0, 4)
				} else {
					r.StopSequences = []string{}
				}
				for !in.IsDelim(']') {
					r.StopSequences = append(r.StopSequences, in.String())
					in.WantComma()
				}
				in.Delim(']')
			}
		case "stream":
			if in.IsNull() {
				in.Skip()
				r.Stream = nil
			} else {
				v := in.Bool()
				r.Stream = &v
			}
		case "metadata":
			if in.IsNull() {
				in.Skip()
				r.Metadata = nil
			} else {
				r.Metadata = &Metadata{}
				r.Metadata.ParseJLexer(in)
			}
		case "thinking":
			if in.IsNull() {
				in.Skip()
				r.Thinking = nil
			} else {
				r.Thinking = &ThinkingConfig{}
				r.Thinking.ParseJLexer(in)
			}
		case "tools":
			if in.IsNull() {
				in.Skip()
				r.Tools = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					r.Tools = make([]*ToolDefinition, 0, 4)
				} else {
					r.Tools = []*ToolDefinition{}
				}
				for !in.IsDelim(']') {
					t := &ToolDefinition{}
					t.ParseJLexer(in)
					r.Tools = append(r.Tools, t)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "tool_choice":
			if in.IsNull() {
				in.Skip()
				r.ToolChoice = nil
			} else {
				r.ToolChoice = &ToolChoice{}
				r.ToolChoice.ParseJLexer(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (m *MessageParam) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "role":
			if in.IsNull() {
				in.Skip()
				m.Role = ""
			} else {
				m.Role = in.String()
			}
		case "content":
			m.Content = parseMessageContentJLexer(in)
		case "name":
			if in.IsNull() {
				in.Skip()
				m.Name = ""
			} else {
				m.Name = in.String()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (s *SystemBlock) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				s.Type = ""
			} else {
				s.Type = in.String()
			}
		case "text":
			if in.IsNull() {
				in.Skip()
				s.Text = ""
			} else {
				s.Text = in.String()
			}
		case "citations":
			if in.IsNull() {
				in.Skip()
				s.Citations = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					s.Citations = make([]json.RawMessage, 0, 4)
				} else {
					s.Citations = []json.RawMessage{}
				}
				for !in.IsDelim(']') {
					s.Citations = append(s.Citations, json.RawMessage(in.Raw()))
					in.WantComma()
				}
				in.Delim(']')
			}
		case "cache_control":
			if in.IsNull() {
				in.Skip()
				s.CacheControl = nil
			} else {
				s.CacheControl = &CacheControl{}
				s.CacheControl.ParseJLexer(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (m *Metadata) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "user_id":
			if in.IsNull() {
				in.Skip()
				m.UserID = nil
			} else {
				v := in.String()
				m.UserID = &v
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (t *ThinkingConfig) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				t.Type = ""
			} else {
				t.Type = in.String()
			}
		case "budget_tokens":
			if in.IsNull() {
				in.Skip()
				t.BudgetTokens = nil
			} else {
				v := in.Int64()
				t.BudgetTokens = &v
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (t *ToolDefinition) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
				t.Name = ""
			} else {
				t.Name = in.String()
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				t.Description = ""
			} else {
				t.Description = in.String()
			}
		case "input_schema":
			if in.IsNull() {
				in.Skip()
				t.InputSchema = json.RawMessage("null")
			} else {
				t.InputSchema = json.RawMessage(in.Raw())
			}
		case "cache_control":
			if in.IsNull() {
				in.Skip()
				t.CacheControl = nil
			} else {
				t.CacheControl = &CacheControl{}
				t.CacheControl.ParseJLexer(in)
			}
		case "max_characters":
			t.MaxCharacters = in.Int()
		case "type":
			if in.IsNull() {
				in.Skip()
				t.Type = ""
			} else {
				t.Type = in.String()
			}
		case "display_width_px":
			t.DisplayWidthPx = in.Int()
		case "display_height_px":
			t.DisplayHeightPx = in.Int()
		case "display_number":
			if in.IsNull() {
				in.Skip()
				t.DisplayNumber = nil
			} else {
				v := in.Int()
				t.DisplayNumber = &v
			}
		case "allowed_domains":
			if in.IsNull() {
				in.Skip()
				t.AllowedDomains = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					t.AllowedDomains = make([]string, 0, 4)
				} else {
					t.AllowedDomains = []string{}
				}
				for !in.IsDelim(']') {
					t.AllowedDomains = append(t.AllowedDomains, in.String())
					in.WantComma()
				}
				in.Delim(']')
			}
		case "blocked_domains":
			if in.IsNull() {
				in.Skip()
				t.BlockedDomains = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					t.BlockedDomains = make([]string, 0, 4)
				} else {
					t.BlockedDomains = []string{}
				}
				for !in.IsDelim(']') {
					t.BlockedDomains = append(t.BlockedDomains, in.String())
					in.WantComma()
				}
				in.Delim(']')
			}
		case "max_uses":
			t.MaxUses = in.Int()
		case "user_location":
			if in.IsNull() {
				in.Skip()
				t.UserLocation = nil
			} else {
				t.UserLocation = &UserLocation{}
				t.UserLocation.ParseJLexer(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (u *UserLocation) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				u.Type = nil
			} else {
				v := in.String()
				u.Type = &v
			}
		case "country":
			if in.IsNull() {
				in.Skip()
				u.Country = nil
			} else {
				v := in.String()
				u.Country = &v
			}
		case "city":
			if in.IsNull() {
				in.Skip()
				u.City = nil
			} else {
				v := in.String()
				u.City = &v
			}
		case "region":
			if in.IsNull() {
				in.Skip()
				u.Region = nil
			} else {
				v := in.String()
				u.Region = &v
			}
		case "timezone":
			if in.IsNull() {
				in.Skip()
				u.Timezone = nil
			} else {
				v := in.String()
				u.Timezone = &v
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (t *ToolChoice) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				t.Type = ""
			} else {
				t.Type = in.String()
			}
		case "name":
			if in.IsNull() {
				in.Skip()
				t.Name = nil
			} else {
				v := in.String()
				t.Name = &v
			}
		case "disable_parallel_tool_use":
			if in.IsNull() {
				in.Skip()
				t.DisableParallelToolUse = nil
			} else {
				v := in.Bool()
				t.DisableParallelToolUse = &v
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (c *CacheControl) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				c.Type = ""
			} else {
				c.Type = in.String()
			}
		case "ttl":
			if in.IsNull() {
				in.Skip()
				c.TTL = nil
			} else {
				v := in.String()
				c.TTL = &v
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (c *Citation) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				c.Type = ""
			} else {
				c.Type = in.String()
			}
		case "cited_text":
			if in.IsNull() {
				in.Skip()
				c.CitedText = ""
			} else {
				c.CitedText = in.String()
			}
		case "document_index":
			c.DocumentIndex = in.Int()
		case "document_title":
			if in.IsNull() {
				in.Skip()
				c.DocumentTitle = ""
			} else {
				c.DocumentTitle = in.String()
			}
		case "start_char_index":
			if in.IsNull() {
				in.Skip()
				c.StartCharIndex = nil
			} else {
				v := in.Int()
				c.StartCharIndex = &v
			}
		case "end_char_index":
			if in.IsNull() {
				in.Skip()
				c.EndCharIndex = nil
			} else {
				v := in.Int()
				c.EndCharIndex = &v
			}
		case "start_page":
			if in.IsNull() {
				in.Skip()
				c.StartPage = nil
			} else {
				v := in.Int()
				c.StartPage = &v
			}
		case "end_page":
			if in.IsNull() {
				in.Skip()
				c.EndPage = nil
			} else {
				v := in.Int()
				c.EndPage = &v
			}
		case "start_block_index":
			if in.IsNull() {
				in.Skip()
				c.StartBlockIndex = nil
			} else {
				v := in.Int()
				c.StartBlockIndex = &v
			}
		case "end_block_index":
			if in.IsNull() {
				in.Skip()
				c.EndBlockIndex = nil
			} else {
				v := in.Int()
				c.EndBlockIndex = &v
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (d *DocumentCitations) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "enabled":
			d.Enabled = in.Bool()
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (s *MessageContentSource) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				s.Type = ""
			} else {
				s.Type = in.String()
			}
		case "media_type":
			if in.IsNull() {
				in.Skip()
				s.MediaType = ""
			} else {
				s.MediaType = in.String()
			}
		case "data":
			if in.IsNull() {
				in.Skip()
				s.Data = json.RawMessage("null")
			} else {
				s.Data = json.RawMessage(in.Raw())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
				s.Content = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					s.Content = make([]MessageContent, 0, 4)
				} else {
					s.Content = []MessageContent{}
				}
				for !in.IsDelim(']') {
					s.Content = append(s.Content, parseMessageContentJLexer(in))
					in.WantComma()
				}
				in.Delim(']')
			}
		case "url":
			if in.IsNull() {
				in.Skip()
				s.Url = ""
			} else {
				s.Url = in.String()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

// --- Content block param parsers ---

func (b *TextBlockParam) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				b.Type = ""
			} else {
				b.Type = in.String()
			}
		case "text":
			if in.IsNull() {
				in.Skip()
				b.Text = ""
			} else {
				b.Text = in.String()
			}
		case "cache_control":
			if in.IsNull() {
				in.Skip()
				b.CacheControl = nil
			} else {
				b.CacheControl = &CacheControl{}
				b.CacheControl.ParseJLexer(in)
			}
		case "citations":
			if in.IsNull() {
				in.Skip()
				b.Citations = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					b.Citations = make([]*Citation, 0, 4)
				} else {
					b.Citations = []*Citation{}
				}
				for !in.IsDelim(']') {
					c := &Citation{}
					c.ParseJLexer(in)
					b.Citations = append(b.Citations, c)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (b *ImageBlockParam) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				b.Type = ""
			} else {
				b.Type = in.String()
			}
		case "source":
			if in.IsNull() {
				in.Skip()
				b.Source = nil
			} else {
				b.Source = &MessageContentSource{}
				b.Source.ParseJLexer(in)
			}
		case "cache_control":
			if in.IsNull() {
				in.Skip()
				b.CacheControl = nil
			} else {
				b.CacheControl = &CacheControl{}
				b.CacheControl.ParseJLexer(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (b *DocumentBlockParam) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				b.Type = ""
			} else {
				b.Type = in.String()
			}
		case "source":
			if in.IsNull() {
				in.Skip()
				b.Source = nil
			} else {
				b.Source = &MessageContentSource{}
				b.Source.ParseJLexer(in)
			}
		case "cache_control":
			if in.IsNull() {
				in.Skip()
				b.CacheControl = nil
			} else {
				b.CacheControl = &CacheControl{}
				b.CacheControl.ParseJLexer(in)
			}
		case "citations":
			if in.IsNull() {
				in.Skip()
				b.Citations = nil
			} else {
				b.Citations = &DocumentCitations{}
				b.Citations.ParseJLexer(in)
			}
		case "context":
			if in.IsNull() {
				in.Skip()
				b.Context = ""
			} else {
				b.Context = in.String()
			}
		case "title":
			if in.IsNull() {
				in.Skip()
				b.Title = ""
			} else {
				b.Title = in.String()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (b *ThinkingBlockParam) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				b.Type = ""
			} else {
				b.Type = in.String()
			}
		case "thinking":
			if in.IsNull() {
				in.Skip()
				b.Thinking = ""
			} else {
				b.Thinking = in.String()
			}
		case "signature":
			if in.IsNull() {
				in.Skip()
				b.Signature = ""
			} else {
				b.Signature = in.String()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (b *RedactedThinkingBlockParam) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				b.Type = ""
			} else {
				b.Type = in.String()
			}
		case "data":
			if in.IsNull() {
				in.Skip()
				b.Data = ""
			} else {
				b.Data = in.String()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (b *ToolUseBlockParam) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				b.Type = ""
			} else {
				b.Type = in.String()
			}
		case "id":
			if in.IsNull() {
				in.Skip()
				b.ID = ""
			} else {
				b.ID = in.String()
			}
		case "name":
			if in.IsNull() {
				in.Skip()
				b.Name = ""
			} else {
				b.Name = in.String()
			}
		case "input":
			if in.IsNull() {
				in.Skip()
				b.Input = json.RawMessage("null")
			} else {
				b.Input = json.RawMessage(in.Raw())
			}
		case "cache_control":
			if in.IsNull() {
				in.Skip()
				b.CacheControl = nil
			} else {
				b.CacheControl = &CacheControl{}
				b.CacheControl.ParseJLexer(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (b *ToolResultBlockParam) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				b.Type = ""
			} else {
				b.Type = in.String()
			}
		case "tool_use_id":
			if in.IsNull() {
				in.Skip()
				b.ToolUseID = ""
			} else {
				b.ToolUseID = in.String()
			}
		case "content":
			b.Content = parseMessageContentJLexer(in)
		case "is_error":
			if in.IsNull() {
				in.Skip()
				b.IsError = nil
			} else {
				v := in.Bool()
				b.IsError = &v
			}
		case "cache_control":
			if in.IsNull() {
				in.Skip()
				b.CacheControl = nil
			} else {
				b.CacheControl = &CacheControl{}
				b.CacheControl.ParseJLexer(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (b *GeneralBlockParam) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				b.Type = ""
			} else {
				b.Type = in.String()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

// --- Polymorphic dispatch helpers ---

// parseSystemContentJLexer handles Kind 2 polymorphic dispatch for SystemContent:
// string, null (→ SystemString("")), or array of SystemBlock.
func parseSystemContentJLexer(in *jlexer.Lexer) SystemContent {
	switch in.CurrentToken() {
	case jlexer.TokenString:
		return SystemString(in.String())
	case jlexer.TokenNull:
		in.Skip()
		return SystemString("")
	case jlexer.TokenDelim:
		if in.IsDelim('[') {
			in.Delim('[')
			var arr SystemBlocks
			if !in.IsDelim(']') {
				arr = make(SystemBlocks, 0, 4)
			} else {
				arr = SystemBlocks{}
			}
			for !in.IsDelim(']') {
				block := &SystemBlock{}
				block.ParseJLexer(in)
				arr = append(arr, *block)
				in.WantComma()
			}
			in.Delim(']')
			return arr
		}
		in.SkipRecursive()
		return nil
	default:
		in.SkipRecursive()
		return nil
	}
}

// parseMessageContentJLexer handles Kind 2 polymorphic dispatch for MessageContent:
// string, null (→ nil), array of ContentBlockParam, or single ContentBlockParam object.
func parseMessageContentJLexer(in *jlexer.Lexer) MessageContent {
	switch in.CurrentToken() {
	case jlexer.TokenString:
		return MessageContentString(in.String())
	case jlexer.TokenNull:
		in.Skip()
		return nil
	case jlexer.TokenDelim:
		if in.IsDelim('[') {
			return parseContentBlockArrayJLexer(in)
		}
		if in.IsDelim('{') {
			block := parseContentBlockParamJLexer(in)
			return MessageContentBlockArray{block}
		}
		in.SkipRecursive()
		return nil
	default:
		in.SkipRecursive()
		return nil
	}
}

// parseContentBlockArrayJLexer parses an array of ContentBlockParam.
func parseContentBlockArrayJLexer(in *jlexer.Lexer) MessageContentBlockArray {
	if in.IsNull() {
		in.Skip()
		return nil
	}
	in.Delim('[')
	var arr MessageContentBlockArray
	if !in.IsDelim(']') {
		arr = make(MessageContentBlockArray, 0, 4)
	} else {
		arr = MessageContentBlockArray{}
	}
	for !in.IsDelim(']') {
		arr = append(arr, parseContentBlockParamJLexer(in))
		in.WantComma()
	}
	in.Delim(']')
	return arr
}

// parseContentBlockParamJLexer handles Kind 3 polymorphic dispatch
// for MessageContentBlockParam using the two-pass Raw() approach.
func parseContentBlockParamJLexer(in *jlexer.Lexer) MessageContentBlockParam {
	if in.IsNull() {
		in.Skip()
		return nil
	}
	rawBytes := in.Raw()
	blockType := extractTypeField(rawBytes)
	parseLex := jlexer.Lexer{Data: rawBytes}
	switch blockType {
	case "text":
		block := &TextBlockParam{}
		block.ParseJLexer(&parseLex)
		return block
	case "image":
		block := &ImageBlockParam{}
		block.ParseJLexer(&parseLex)
		return block
	case "document":
		block := &DocumentBlockParam{}
		block.ParseJLexer(&parseLex)
		return block
	case "thinking":
		block := &ThinkingBlockParam{}
		block.ParseJLexer(&parseLex)
		return block
	case "redacted_thinking":
		block := &RedactedThinkingBlockParam{}
		block.ParseJLexer(&parseLex)
		return block
	case "tool_use":
		block := &ToolUseBlockParam{}
		block.ParseJLexer(&parseLex)
		return block
	case "tool_result":
		block := &ToolResultBlockParam{}
		block.ParseJLexer(&parseLex)
		return block
	default:
		block := &GeneralBlockParam{}
		block.ParseJLexer(&parseLex)
		return block
	}
}

// extractTypeField scans a JSON object and returns the value of the "type" field.
func extractTypeField(data []byte) string {
	lex := jlexer.Lexer{Data: data}
	lex.Delim('{')
	for !lex.IsDelim('}') {
		key := lex.UnsafeFieldName(false)
		lex.WantColon()
		if key == "type" {
			return lex.String()
		}
		lex.SkipRecursive()
		lex.WantComma()
	}
	return ""
}
