backends:
  infini:
    base_url: https://cloud.infini-ai.com/maas
    url_path_chat: /v1/chat/completions

models:
  kimi-k2-instruct:
    access: public
    # use default_rules to deny stream request
    default_rules:
      - name: deny_stream
        match: "RawReq.stream == true"
        deny:
          reason_text: "stream is not allowed"
          http_status_code: 403
    backends:
      default:1: 
        use: infini
        limiter:
          tpm: 1000
          rpm: 1000
          # concurrency: 10
          rpm_marker_rates: [1000, 2000, 3000]
          rpm_limiter_rates: [1000, 2000, 3000]
          concurrency_marker_rates: [1000, 2000, 3000]
          concurrency_limiter_rates: [1000, 2000, 3000]
          # deny_when_exceeding: true

      force_stream:
        use: infini
        request_rewrites:
          set_keys:
            stream: true

users:
  org1:
    api_keys:
      user1: octo-12345
    models:
      kimi-k2-instruct:
        # allow users in org1 to use force_stream backend
        rules:
          - name: allow_force_stream
            match: "RawReq.force_stream == true"
            forward_weights:
              force_stream: 10
              non_exist: 20
            rule_limits:
              tpm: 1000
              rpm: 1000
              # concurrency: 10
              concurrency_marker_rates: [1000, 2000, 3000]
              concurrency_limiter_rates: [1000, 2000, 3000]
              # deny_when_exceeding: true
