// Code generated by AI. DO NOT EDIT manually without reading the generation guide.
//
// This file contains jlexer streaming parsers for the structs defined in:
//   pkg/types/openai/chatcompletion_req.go
//
// Source file SHA-256: f16ae6ea0c31b986b8c502692cf30c62cbd7e9414db5116d798f9b3e7b60b090
//
// Generation guide: pkg/types/JLEXER_PARSER_GUIDE.md
// Polymorphic field patterns: pkg/types/UNION_TYPES.md
//
// If the struct definitions in the source file change, regenerate this file
// following the generation guide. Verify the source hash with:
//   shasum -a 256 pkg/types/openai/chatcompletion_req.go

package openai

import (
	"encoding/json"

	"github.com/mailru/easyjson/jlexer"
)

func (r *ChatCompletionRequest) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "model":
			if in.IsNull() {
				in.Skip()
				r.Model = ""
			} else {
				r.Model = in.String()
			}
		case "messages":
			if in.IsNull() {
				in.Skip()
				r.Messages = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					r.Messages = make([]*Message, 0, 4)
				} else {
					r.Messages = []*Message{}
				}
				for !in.IsDelim(']') {
					m := &Message{}
					m.ParseJLexer(in)
					r.Messages = append(r.Messages, m)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "thinking":
			if in.IsNull() {
				in.Skip()
				r.Thinking = nil
			} else {
				r.Thinking = &Thinking{}
				r.Thinking.ParseJLexer(in)
			}
		case "max_tokens":
			if in.IsNull() {
				in.Skip()
				r.MaxTokens = nil
			} else {
				v := in.Int()
				r.MaxTokens = &v
			}
		case "max_completion_tokens":
			if in.IsNull() {
				in.Skip()
				r.MaxCompletionTokens = nil
			} else {
				v := in.Int()
				r.MaxCompletionTokens = &v
			}
		case "temperature":
			if in.IsNull() {
				in.Skip()
				r.Temperature = nil
			} else {
				v := in.Float64()
				r.Temperature = &v
			}
		case "top_p":
			if in.IsNull() {
				in.Skip()
				r.TopP = nil
			} else {
				v := in.Float64()
				r.TopP = &v
			}
		case "top_k":
			if in.IsNull() {
				in.Skip()
				r.TopK = nil
			} else {
				v := in.Int()
				r.TopK = &v
			}
		case "stop":
			r.Stop = parseStopValueJLexer(in)
		case "stream":
			if in.IsNull() {
				in.Skip()
				r.Stream = nil
			} else {
				v := in.Bool()
				r.Stream = &v
			}
		case "tools":
			if in.IsNull() {
				in.Skip()
				r.Tools = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					r.Tools = make([]*Tool, 0, 4)
				} else {
					r.Tools = []*Tool{}
				}
				for !in.IsDelim(']') {
					tool := &Tool{}
					tool.ParseJLexer(in)
					r.Tools = append(r.Tools, tool)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "tool_choice":
			r.ToolChoice = parseToolChoiceValueJLexer(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (t *Thinking) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				t.Type = ""
			} else {
				t.Type = in.String()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (t *Tool) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				t.Type = ""
			} else {
				t.Type = in.String()
			}
		case "function":
			if in.IsNull() {
				in.Skip()
				t.Function = nil
			} else {
				t.Function = &ToolFunction{}
				t.Function.ParseJLexer(in)
			}
		case "custom":
			if in.IsNull() {
				in.Skip()
				t.Custom = nil
			} else {
				t.Custom = &CustomTool{}
				t.Custom.ParseJLexer(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (t *ToolFunction) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
				t.Name = nil
			} else {
				v := in.String()
				t.Name = &v
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				t.Description = nil
			} else {
				v := in.String()
				t.Description = &v
			}
		case "parameters":
			if in.IsNull() {
				in.Skip()
				t.Parameters = json.RawMessage("null")
			} else {
				t.Parameters = json.RawMessage(in.Raw())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (c *CustomTool) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
				c.Name = ""
			} else {
				c.Name = in.String()
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				c.Description = ""
			} else {
				c.Description = in.String()
			}
		case "format":
			if in.IsNull() {
				in.Skip()
				c.Format = json.RawMessage("null")
			} else {
				c.Format = json.RawMessage(in.Raw())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (t *ToolChoiceObject) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				t.Type = ""
			} else {
				t.Type = in.String()
			}
		case "function":
			if in.IsNull() {
				in.Skip()
				t.Function = nil
			} else {
				t.Function = &ToolChoiceFunction{}
				t.Function.ParseJLexer(in)
			}
		case "allowed_tools":
			if in.IsNull() {
				in.Skip()
				t.AllowedTools = nil
			} else {
				t.AllowedTools = &ToolChoiceAllowedTools{}
				t.AllowedTools.ParseJLexer(in)
			}
		case "custom":
			if in.IsNull() {
				in.Skip()
				t.Custom = nil
			} else {
				t.Custom = &ToolChoiceCustom{}
				t.Custom.ParseJLexer(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (t *ToolChoiceFunction) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
				t.Name = ""
			} else {
				t.Name = in.String()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (t *ToolChoiceAllowedTools) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "mode":
			if in.IsNull() {
				in.Skip()
				t.Mode = ""
			} else {
				t.Mode = in.String()
			}
		case "tools":
			if in.IsNull() {
				in.Skip()
				t.Tools = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					t.Tools = make([]map[string]interface{}, 0, 4)
				} else {
					t.Tools = []map[string]interface{}{}
				}
				for !in.IsDelim(']') {
					v := in.Interface()
					if m, ok := v.(map[string]interface{}); ok {
						t.Tools = append(t.Tools, m)
					} else {
						t.Tools = append(t.Tools, nil)
					}
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (t *ToolChoiceCustom) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
				t.Name = ""
			} else {
				t.Name = in.String()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

// parseStopValueJLexer handles Kind 2 polymorphic dispatch for StopValue:
// the value can be a string, an array of strings, or null.
// Note: for null, json.Unmarshal([]byte("null"), &str) succeeds with str="",
// so the Field wrapper produces StopString(""). We match that behavior.
func parseStopValueJLexer(in *jlexer.Lexer) StopValue {
	switch in.CurrentToken() {
	case jlexer.TokenString:
		return StopString(in.String())
	case jlexer.TokenNull:
		in.Skip()
		return StopString("")
	case jlexer.TokenDelim:
		if in.IsDelim('[') {
			in.Delim('[')
			var arr StopArray
			if !in.IsDelim(']') {
				arr = make(StopArray, 0, 4)
			} else {
				arr = StopArray{}
			}
			for !in.IsDelim(']') {
				arr = append(arr, in.String())
				in.WantComma()
			}
			in.Delim(']')
			return arr
		}
		in.SkipRecursive()
		return nil
	default:
		in.SkipRecursive()
		return nil
	}
}

// parseToolChoiceValueJLexer handles Kind 2 polymorphic dispatch for ToolChoiceValue:
// the value can be a string, an object, or null.
// Note: for null, json.Unmarshal([]byte("null"), &str) succeeds with str="",
// so the Field wrapper produces ToolChoiceString(""). We match that behavior.
func parseToolChoiceValueJLexer(in *jlexer.Lexer) ToolChoiceValue {
	switch in.CurrentToken() {
	case jlexer.TokenString:
		return ToolChoiceString(in.String())
	case jlexer.TokenNull:
		in.Skip()
		return ToolChoiceString("")
	case jlexer.TokenDelim:
		if in.IsDelim('{') {
			obj := ToolChoiceObject{}
			obj.ParseJLexer(in)
			return obj
		}
		in.SkipRecursive()
		return nil
	default:
		in.SkipRecursive()
		return nil
	}
}

func (m *Message) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "role":
			if in.IsNull() {
				in.Skip()
				m.Role = ""
			} else {
				m.Role = in.String()
			}
		case "name":
			if in.IsNull() {
				in.Skip()
				m.Name = ""
			} else {
				m.Name = in.String()
			}
		case "tool_call_id":
			if in.IsNull() {
				in.Skip()
				m.ToolCallID = ""
			} else {
				m.ToolCallID = in.String()
			}
		case "content":
			m.Content = parseMessageContentJLexer(in)
		case "reasoning_content":
			m.ReasoningContent = parseMessageContentJLexer(in)
		case "tool_calls":
			if in.IsNull() {
				in.Skip()
				m.ToolCalls = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					m.ToolCalls = make([]*MessageToolCall, 0, 4)
				} else {
					m.ToolCalls = []*MessageToolCall{}
				}
				for !in.IsDelim(']') {
					tc := &MessageToolCall{}
					tc.ParseJLexer(in)
					m.ToolCalls = append(m.ToolCalls, tc)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

// parseMessageContentJLexer handles the Kind 2 polymorphic dispatch for MessageContent:
// the value can be a string, an array of content items, or null.
// Note: for null, json.Unmarshal([]byte("null"), &str) succeeds with str="",
// so the Field wrapper produces MessageContentString(""). We match that behavior.
func parseMessageContentJLexer(in *jlexer.Lexer) MessageContent {
	switch in.CurrentToken() {
	case jlexer.TokenString:
		return MessageContentString(in.String())
	case jlexer.TokenNull:
		in.Skip()
		return MessageContentString("")
	case jlexer.TokenDelim:
		if in.IsDelim('[') {
			in.Delim('[')
			var arr MessageContentArray
			if !in.IsDelim(']') {
				arr = make(MessageContentArray, 0, 4)
			} else {
				arr = MessageContentArray{}
			}
			for !in.IsDelim(']') {
				item := &MessageContentItem{}
				item.ParseJLexer(in)
				arr = append(arr, item)
				in.WantComma()
			}
			in.Delim(']')
			return arr
		}
		in.SkipRecursive()
		return nil
	default:
		in.SkipRecursive()
		return nil
	}
}

func (tc *MessageToolCall) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
				tc.ID = ""
			} else {
				tc.ID = in.String()
			}
		case "index":
			tc.Index = in.Int()
		case "type":
			if in.IsNull() {
				in.Skip()
				tc.Type = ""
			} else {
				tc.Type = in.String()
			}
		case "function":
			if in.IsNull() {
				in.Skip()
				tc.Function = nil
			} else {
				tc.Function = &ToolCallFunction{}
				tc.Function.ParseJLexer(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (f *ToolCallFunction) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
				f.Name = ""
			} else {
				f.Name = in.String()
			}
		case "arguments":
			if in.IsNull() {
				in.Skip()
				f.Arguments = ""
			} else {
				f.Arguments = in.String()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (item *MessageContentItem) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
				item.Type = ""
			} else {
				item.Type = in.String()
			}
		case "text":
			if in.IsNull() {
				in.Skip()
				item.Text = ""
			} else {
				item.Text = in.String()
			}
		case "image_url":
			item.ImageURL = parseImageURLContentJLexer(in)
		case "video_url":
			if in.IsNull() {
				in.Skip()
				item.VideoURL = nil
			} else {
				item.VideoURL = &MessageContentItemVideoURL{}
				item.VideoURL.ParseJLexer(in)
			}
		case "audio_url":
			if in.IsNull() {
				in.Skip()
				item.AudioURL = nil
			} else {
				item.AudioURL = &MessageContentItemAudioURL{}
				item.AudioURL.ParseJLexer(in)
			}
		case "input_audio":
			if in.IsNull() {
				in.Skip()
				item.InputAudio = nil
			} else {
				item.InputAudio = &MessageContentItemInputAudio{}
				item.InputAudio.ParseJLexer(in)
			}
		case "file":
			if in.IsNull() {
				in.Skip()
				item.File = nil
			} else {
				item.File = &MessageContentItemFile{}
				item.File.ParseJLexer(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

// parseImageURLContentJLexer handles the Kind 2 polymorphic dispatch for ImageURLContent:
// the value can be a string (URL only), an object with url/detail fields, or null.
// Note: for null, json.Unmarshal([]byte("null"), &str) succeeds with str="",
// so the Field wrapper produces MessageContentItemImageURLString(""). We match that behavior.
func parseImageURLContentJLexer(in *jlexer.Lexer) ImageURLContent {
	switch in.CurrentToken() {
	case jlexer.TokenString:
		return MessageContentItemImageURLString(in.String())
	case jlexer.TokenNull:
		in.Skip()
		return MessageContentItemImageURLString("")
	case jlexer.TokenDelim:
		if in.IsDelim('{') {
			obj := &MessageContentItemImageURL{}
			obj.ParseJLexer(in)
			return obj
		}
		in.SkipRecursive()
		return nil
	default:
		in.SkipRecursive()
		return nil
	}
}

func (img *MessageContentItemImageURL) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "url":
			if in.IsNull() {
				in.Skip()
				img.URL = ""
			} else {
				img.URL = in.String()
			}
		case "detail":
			if in.IsNull() {
				in.Skip()
				img.Detail = ""
			} else {
				img.Detail = in.String()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v *MessageContentItemVideoURL) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "url":
			if in.IsNull() {
				in.Skip()
				v.URL = ""
			} else {
				v.URL = in.String()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (a *MessageContentItemAudioURL) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "url":
			if in.IsNull() {
				in.Skip()
				a.URL = ""
			} else {
				a.URL = in.String()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (a *MessageContentItemInputAudio) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
				a.Data = ""
			} else {
				a.Data = in.String()
			}
		case "format":
			if in.IsNull() {
				in.Skip()
				a.Format = ""
			} else {
				a.Format = in.String()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (f *MessageContentItemFile) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "file_uri":
			if in.IsNull() {
				in.Skip()
				f.FileURI = ""
			} else {
				f.FileURI = in.String()
			}
		case "mime_type":
			if in.IsNull() {
				in.Skip()
				f.MIMEType = ""
			} else {
				f.MIMEType = in.String()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
