// Code generated by AI. DO NOT EDIT manually without reading the generation guide.
//
// This file contains jlexer streaming parsers for the structs defined in:
//   pkg/types/openai/chatcompletion_resp.go
//
// Source file SHA-256: 478ac2397f588761ee11dab540b87eac227282fd8356a7d2a99f9b2e7f65e2d5
//
// Generation guide: pkg/types/JLEXER_PARSER_GUIDE.md
// Polymorphic field patterns: pkg/types/UNION_TYPES.md
//
// If the struct definitions in the source file change, regenerate this file
// following the generation guide. Verify the source hash with:
//   shasum -a 256 pkg/types/openai/chatcompletion_resp.go

package openai

import (
	"github.com/mailru/easyjson/jlexer"
)

func (r *ChatCompletionResponse) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
				r.ID = ""
			} else {
				r.ID = in.String()
			}
		case "created":
			r.Created = in.Int()
		case "object":
			if in.IsNull() {
				in.Skip()
				r.Object = ""
			} else {
				r.Object = in.String()
			}
		case "model":
			if in.IsNull() {
				in.Skip()
				r.Model = ""
			} else {
				r.Model = in.String()
			}
		case "choices":
			if in.IsNull() {
				in.Skip()
				r.Choices = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					r.Choices = make([]*ChatCompletionChoice, 0, 4)
				} else {
					r.Choices = []*ChatCompletionChoice{}
				}
				for !in.IsDelim(']') {
					choice := &ChatCompletionChoice{}
					choice.ParseJLexer(in)
					r.Choices = append(r.Choices, choice)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "usage":
			if in.IsNull() {
				in.Skip()
				r.Usage = nil
			} else {
				r.Usage = &Usage{}
				r.Usage.ParseJLexer(in)
			}
		case "blocked":
			if in.IsNull() {
				in.Skip()
				r.Blocked = nil
			} else {
				v := in.Bool()
				r.Blocked = &v
			}
		case "system_fingerprint":
			if in.IsNull() {
				in.Skip()
				r.SystemFingerprint = nil
			} else {
				v := in.String()
				r.SystemFingerprint = &v
			}
		case "service_tier":
			if in.IsNull() {
				in.Skip()
				r.ServiceTier = nil
			} else {
				v := in.String()
				r.ServiceTier = &v
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (c *ChatCompletionChoice) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "finish_reason":
			if in.IsNull() {
				in.Skip()
				c.FinishReason = ""
			} else {
				c.FinishReason = in.String()
			}
		case "index":
			c.Index = in.Int()
		case "message":
			if in.IsNull() {
				in.Skip()
				c.Message = nil
			} else {
				c.Message = &Message{}
				c.Message.ParseJLexer(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (c *ChatCompletionStreamChunk) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
				c.ID = ""
			} else {
				c.ID = in.String()
			}
		case "created":
			c.Created = in.Int()
		case "object":
			if in.IsNull() {
				in.Skip()
				c.Object = ""
			} else {
				c.Object = in.String()
			}
		case "model":
			if in.IsNull() {
				in.Skip()
				c.Model = ""
			} else {
				c.Model = in.String()
			}
		case "system_fingerprint":
			if in.IsNull() {
				in.Skip()
				c.SystemFingerprint = nil
			} else {
				v := in.String()
				c.SystemFingerprint = &v
			}
		case "service_tier":
			if in.IsNull() {
				in.Skip()
				c.ServiceTier = nil
			} else {
				v := in.String()
				c.ServiceTier = &v
			}
		case "choices":
			if in.IsNull() {
				in.Skip()
				c.Choices = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					c.Choices = make([]*ChatCompletionStreamChoice, 0, 4)
				} else {
					c.Choices = []*ChatCompletionStreamChoice{}
				}
				for !in.IsDelim(']') {
					choice := &ChatCompletionStreamChoice{}
					choice.ParseJLexer(in)
					c.Choices = append(c.Choices, choice)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "usage":
			if in.IsNull() {
				in.Skip()
				c.Usage = nil
			} else {
				c.Usage = &Usage{}
				c.Usage.ParseJLexer(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (c *ChatCompletionStreamChoice) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "finish_reason":
			if in.IsNull() {
				in.Skip()
				c.FinishReason = ""
			} else {
				c.FinishReason = in.String()
			}
		case "index":
			c.Index = in.Int()
		case "delta":
			if in.IsNull() {
				in.Skip()
				c.Delta = nil
			} else {
				c.Delta = &Message{}
				c.Delta.ParseJLexer(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (u *Usage) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "completion_tokens":
			u.CompletionTokens = in.Int()
		case "prompt_tokens":
			u.PromptTokens = in.Int()
		case "total_tokens":
			u.TotalTokens = in.Int()
		case "completion_tokens_details":
			if in.IsNull() {
				in.Skip()
				u.CompletionTokensDetails = nil
			} else {
				u.CompletionTokensDetails = &CompletionTokensDetails{}
				u.CompletionTokensDetails.ParseJLexer(in)
			}
		case "prompt_tokens_details":
			if in.IsNull() {
				in.Skip()
				u.PromptTokensDetails = nil
			} else {
				u.PromptTokensDetails = &PromptTokensDetails{}
				u.PromptTokensDetails.ParseJLexer(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (d *CompletionTokensDetails) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "reasoning_tokens":
			d.ReasoningTokens = in.Int()
		case "audio_tokens":
			d.AudioTokens = in.Int()
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (d *PromptTokensDetails) ParseJLexer(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "cached_tokens":
			d.CachedTokens = in.Int()
		case "audio_tokens":
			d.AudioTokens = in.Int()
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
